export const constants = {
    loginTitle: 'Login to your account',
    labelMail: 'Email',
    mailValidation: 'The input is not valid E-mail!',
    mailRequired: 'Please input your E-mail!',
    mailPlaceholder: 'ivanov@gmail.com',
    passwordLabel: 'Password',
    passwordRequired: 'Please input your password!',
    passwordLength: 'Password must be at least 8 characters long!',
    passwordUpperCase: 'Password must contain at least one uppercase letter!',
    passwordLowerCase: 'Password must contain at least one lowercase letter!',
    passwordDigit: 'Password must contain at least one digit!',
    passwordSymbol: 'Password must contain at least one symbol!',
    passwordPlaceholder: '********',
    loginButton: 'Log in',
    signUpLoginForm: "Don't have an account?",
    signUpText: 'Sign up!',
    title: 'Get things done!',
    logOut: 'Log out',
    taskInputPlaceholder: 'What is the task today?',
    buttonAddTask: 'Add task',
    buttonEditTask: 'Update',
    ageLabel: 'Age',
    ageRequired: 'Please input your age!',
    ageValidation: 'Please input the correct age!',
    agePlaceholder: '23',
    successfullSubmit: 'The account was created successfully.',
    registrationFormTitle: 'Registration form',
    usernameLabel: 'Username',
    nameRequired: 'Please input your name!',
    namePlaceholder: 'Ivan',
    genderLabel: 'Gender',
    genderRequired: 'Please input your gender!',
    genderPlaceholder: 'Select your gender',
    genderMale: 'male',
    genderFemale: 'female',
    textForLoginRegistrationForm: 'Already have an account?',
    loginText: 'Log in',
    errorTitle: 'Oops!',
    errorText: 'Sorry, an unexpected error has occurred.',
    inputValadationError: 'The field cannot be empty, please enter a task.',
};
